name: Build master

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

env:
  UPSTREAM_OWNER: joshuamerold
  REPOSITORY_NAME: dayz-sa-server-docker
  CONTAINER_REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ env.UPSTREAM_OWNER }}/${{ env.REPOSITORY_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ env.UPSTREAM_OWNER }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.UPSTREAM_OWNER }}/${{ env.REPOSITORY_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.UPSTREAM_OWNER }}/${{ env.REPOSITORY_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ env.REGISTRY }}/${{ env.UPSTREAM_OWNER }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}